### PR TITLE
Added Github-compatible docs

### PR DESCRIPTION
**Pull request by RReverser**
* Renamed to README.md for proper rendering on Github.
* Added docs from the original website, so that repo becomes self-descriptive.
* Updated Colm link in README to the corresponding repo as 0.13.0.2 is not compatible anymore.

You can see how the repo looks like after modifications here: https://github.com/RReverser/ragel/tree/readme-md

### CODE REVIEW

**Comment by colmnet** [comment]
Would prefer to keep a simple README. Don't like tailoring the readme name to github conventions, just because it's mirrored there. Also, a copy of the home page is a bit excessive for a readme. There will be two places to maintain the info and it will compete with the homepage for views.

**Comment by RReverser** [comment]
Ok, np. I just thought that Github is not a mirror but a primary place now, and for such cases projects usually have full info available on the repo page. I see it's not your case.

Could you maybe add the link to the official page with docs then? (Github has place for that right near the repo description)

**Comment by colmnet** [comment]
Done.

**Comment by RReverser** [comment]
Thanks. Oh, and another thing that I fixed was changing the link to Colm repo since Ragel doesn't build with Colm 0.13.0.2 but needs the latest version (as you pointed me in #1).

**Pull request closed without merging**
